//<auto-generated />
namespace ps.platform.test
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using Microsoft.Hadoop.Avro;

    /// <summary>
    /// Used to serialize and deserialize Avro record ps.platform.test.Username.
    /// </summary>
    [DataContract(Namespace = "ps.platform.test")]
    public partial class Username
    {
        private const string JsonSchema = @"{""type"":""record"",""name"":""ps.platform.test.Username"",""fields"":[{""name"":""username"",""type"":""string""}]}";

        /// <summary>
        /// Gets the schema.
        /// </summary>
        public static string Schema
        {
            get
            {
                return JsonSchema;
            }
        }
      
        /// <summary>
        /// Gets or sets the username field.
        /// </summary>
        [DataMember]
        public string username { get; set; }
                
        /// <summary>
        /// Initializes a new instance of the <see cref="Username"/> class.
        /// </summary>
        public Username()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Username"/> class.
        /// </summary>
        /// <param name="username">The username.</param>
        public Username(string username)
        {
            this.username = username;
        }
    }
}
